---
- name: Configure bibata cursor
  block:
    - name: Setup default configuration
      ansible.builtin.include_tasks:
        file: noauto_configure_default.yml

    - name: Setup gtk configuration
      ansible.builtin.include_tasks:
        file: noauto_configure_gtk.yml

    - name: Setup Xresources for i3 and X11-based environments
      ansible.builtin.include_tasks:
        file: noauto_configure_xresources.yml
