---
- name: Check installed bibata cursor version
  block:
    - name: Check installed bibata_cursor version OS-specifically from package manager
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "noauto_check_installed_version_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_check_installed_version_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_check_installed_version_{{ ansible_distribution }}.yml"
        - "noauto_check_installed_version_{{ ansible_os_family }}.yml"
        - "noauto_check_installed_version_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file
      when: bibata_cursor_installed_version is not defined

    - name: Import installed bibata cursor version from source check
      ansible.builtin.include_tasks: noauto_check_installed_version_source.yml
      when:
        - bibata_cursor_installed_from is not defined
          or bibata_cursor_installed_from != "package manager"
