---
- name: Uninstall current installation of bibata cursor
  block:
    - name: Uninstall bibata cursor OS-specifically from package manager
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "noauto_uninstall_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_uninstall_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_uninstall_{{ ansible_distribution }}.yml"
        - "noauto_uninstall_{{ ansible_os_family }}.yml"
        - "noauto_uninstall_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file

    - name: Check installed bibata_cursor version
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "noauto_check_installed_version_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_check_installed_version_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_check_installed_version_{{ ansible_distribution }}.yml"
        - "noauto_check_installed_version_{{ ansible_os_family }}.yml"
        - "noauto_check_installed_version_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file

    - name: Uninstall bibata cursor from source
      ansible.builtin.include_tasks: noauto_uninstall_source.yml
      when: bibata_cursor_installed_version is defined and bibata_cursor_installed_version != ""
