---
- name: Setup gtk configuration
  block:
    - name: Import installed gtk version check
      ansible.builtin.include_tasks: noauto_check_installed_gtk_version.yml
      when: bibata_cursor_installed_gtk_version is not defined

    - name: Check if a user-specific gtk configuration file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.config/{{ bibata_cursor_installed_gtk_major_dir }}/settings.ini"
      register: bibata_cursor_user_gtk

    - name: Fail if user-specific gtk configuration file exists
      ansible.builtin.fail:
        msg: "Please remove user-specific gtk configuration in ~/.config/{{ bibata_cursor_installed_gtk_major_dir }}/settings.ini"
      when: bibata_cursor_user_gtk.stat.exists

    - name: Ensure gtk configuration folder exists
      ansible.builtin.file:
        path: "/usr/share/{{ bibata_cursor_installed_gtk_major_dir }}"
        state: directory
        mode: "755"
        owner: root
        group: root
      become: true

    - name: Ensure gtk configuration includes cursor name
      community.general.ini_file:
        path: "/usr/share/{{ bibata_cursor_installed_gtk_major_dir }}/settings.ini"
        section: Settings
        option: gtk-cursor-theme-name
        value: Bibata-Modern-{{ bibata_cursor_type }}
        state: present
        mode: "644"
        owner: root
        group: root
      become: true

    - name: Ensure gtk configuration includes cursor size
      community.general.ini_file:
        path: "/usr/share/{{ bibata_cursor_installed_gtk_major_dir }}/settings.ini"
        section: Settings
        option: gtk-cursor-theme-size
        value: "{{ bibata_cursor_size }}"
        state: present
        mode: "644"
        owner: root
        group: root
      become: true
