---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Install bibata cursor dependencies via apt
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Ensure bibata cursor dependencies are installed
      ansible.builtin.apt:
        name: "{{ bibata_cursor_dep_pkgs }}"
        state: present
      become: true
